name: 'AppendToFile Action'
description: 'Appends text to a file (if it is not already there)'
inputs:
  issueNumber:
    description: 'The number of the newly created issue'
    required: true
  assignee:
    description: 'The person (username) being assigned to the issue'
    required: true
runs:
  using: 'node16'
  main: 'index.js'
